# Generated by Django 4.2.2 on 2023-06-24 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('type', models.CharField(max_length=128, verbose_name='Тип')),
                ('area', models.CharField(max_length=16, verbose_name='Площадь')),
                ('floor', models.CharField(max_length=16, verbose_name='Этаж')),
                ('location', models.CharField(max_length=512, verbose_name='Локация')),
                ('year', models.IntegerField(verbose_name='Год постройки')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='apartment/', verbose_name='')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='realtyapp.apartment')),
            ],
        ),
    ]
