# Generated by Django 4.2.2 on 2023-06-25 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realtyapp', '0002_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='station',
            field=models.CharField(blank=True, default='Первомайская', max_length=256, null=True, verbose_name='Метро'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
