# Generated by Django 4.2.2 on 2023-06-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtyapp', '0004_purchases'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='category',
            field=models.CharField(choices=[('New Buildings', 'New Buildings'), ('Houses', 'Houses'), ('Garages', 'Garages')], default='New Buildings', max_length=128, verbose_name='Категория'),
        ),
    ]
