# Generated by Django 4.2.2 on 2023-06-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtyapp', '0006_alter_apartment_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentimage',
            name='image',
            field=models.ImageField(upload_to='apartment_images/', verbose_name=''),
        ),
    ]
